In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#importing dataset 
dataset = pd.read_csv('Bank_Data.csv')
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values

In [5]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [8]:
#Encoding categorical data, when we have categorical data use Lableencoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])

In [10]:
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])

In [11]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [13]:
x = x[:,1:] #To avoid dummy variable trap, leads to correlation of variables hence we avoid it

In [14]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
#if your output is categorical value i.e y = 0,1,2
#use
#labelencoder_y = LabelEncoder()
#y = labelencoder_y.fit_transform(y)

In [16]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [17]:
#feature scaling is a must in nueral network, as we have large number of data leading to heavy computational
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
#lets create an ANN
#import the keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [19]:
#feedforward is a sequential network hence model is sequential

In [20]:
#to represent the number of layers in the ANN, we use dense

In [21]:
#initialising ANN
classifier = Sequential()

In [22]:
#Adding the input layer and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [23]:
#init = uniform is the initializing weights such that weights values are closer to zero
#1.what are other methods to initialize weights?

In [24]:
#adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [25]:
#2.overfitting in ANN, how it happens, how to avoid it?

In [26]:
#3.perform the same model coding for the theory question solved in class?

In [27]:
#Adding the output layer
classifier.add(Dense(output_dim=1, init = 'uniform', activation='sigmoid'))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [28]:
#Compile the ANN
#adam is the gradient discent technique, used to get the error for weight updation
#binary_crossentropy fn is used to get hold of loss at the end of the iteration
classifier.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
#fitting th ANN to the training set
classifier.fit(x_train,y_train, batch_size=10, nb_epoch = 100)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4805 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4298 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.4245 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4189 - acc: 0.8167
Epoch 5/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4159 - acc: 0.8259
Epoch 6/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4137 - acc: 0.8292
Epoch 7/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4124 - acc: 0.8291
Epoch 8/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4107 - acc: 0.8319
Epoch 9/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4097 - acc: 0.8337
Epoch 10/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4087 - acc: 0.8330

In [30]:
#prediction
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [31]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [32]:
#confusionmatrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [33]:
cm

array([[1555,   40],
       [ 280,  125]])

In [34]:
TP = cm[1,1]
FP = cm[0,1]
TN = cm[1,0]
FN = cm[0,0]
Total = (TP+FP+TN+FN)

In [35]:
Acc = (TP+FN)/Total

In [36]:
Acc

0.84